# -*- encoding: utf-8 -*-
"""
    keys

    string constants
"""

ALLOW_SOURCE = 'allow_source'
ALLOW_SPECTRE = 'allow_spectre'
BROADCAST_TYPE = 'broadcast_type'
BROADCASTS = 'broadcasts'
CHANNEL = 'channel'
CHANNEL_ID = 'channel_id'
COMMUNITIES = 'communities'
COMMUNITY_ID = 'community_id'
CURSOR = 'cursor'
CLIENT_ID = 'client_id'
DIRECTION = 'direction'
EMOTESETS = 'emotesets'
ERROR = 'error'
FEATURED = 'featured'
FOLLOWS = 'follows'
GAME = 'game'
HLS = 'hls'
ID = 'id'
LANGUAGE = 'language'
LIMIT = 'limit'
LIVE = 'live'
MESSAGE = 'message'
NAME = 'name'
NAUTH = 'nauth'
NAUTHSIG = 'nauthsig'
NEED_HTTPS = 'need_https'
NOTIFICATION = 'notification'
OFFSET = 'offset'
PERIOD = 'period'
QUERY = 'query'
SIG = 'sig'
SORT_BY = 'sortby'
STREAM_TYPE = 'stream_type'
TARGET = 'target'
TEAM = 'team'
TOKEN = 'token'
TYPE = 'type'
USER = 'user'
USER_AGENT = 'User-Agent'
USER_AGENT_STRING = ('Mozilla/5.0 (Windows NT 6.1; WOW64; rv:6.0) '
                     'Gecko/20100101 Firefox/6.0')
VOD = 'vod'
