name: Add-on Validations

on:
  push:
    branches: [ master, main ]

  pull_request:
    branches: [ master, main ]

jobs:
  addon-validations:
    if: github.repository == 'anxdpanic/script.module.python.twitch'

    runs-on: ubuntu-latest
    name: Add-on Validations

    steps:
      - name: Checkout Add-on
        uses: actions/checkout@v2
        with:
          path: ${{ github.event.repository.name }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install git+https://github.com/xbmc/addon-check.git
          sudo apt-get install xmlstarlet

      - name: Kodi Add-on Checker (Isengard)
        id: kodi-addon-checker-isengard
        run: |
          kodi-addon-checker ${{ github.event.repository.name }} --branch=isengard

      - name: Staging for Official Repository (Matrix)
        id: stage-matrix
        run: |
          xmlstarlet ed -L -u '//import[@addon="xbmc.python"]/@version' -v "3.0.0" addon.xml
          version=$(xmlstarlet sel -t -v 'string(/addon/@version)' addon.xml)
          xmlstarlet ed -L -u '/addon/@version' -v "${version}+matrix.1" addon.xml
        working-directory: ${{ github.event.repository.name }}

      - name: Kodi Add-on Checker (Matrix)
        id: kodi-addon-checker-matrix
        run: |
          kodi-addon-checker ${{ github.event.repository.name }} --branch=matrix
